#
#
# CREATE A COPY OF THIS FILE AND STORE THE LOCATION IN 
# THE ENVIRONMENT VARIABLE XERO_TEST_CONFIG TO ENABLE
# WHEN PERFORMING A 'make test'
#
# by default test will try to load t/config/test_config.ini
# THIS ENV WILL ALSO WORK FOR COMMAND LINE WHERE VALUES
# ARE NOT PASSED INTO THE CONSTRUCTOR
#
# See README and 'perldoc WebService::Xero' for more detail
#

[PRIVATE_APPLICATION]
CONSUMER_KEY    = B6DMPEODCW67U8KETSPWA9ZHXT7TQP
CONSUMER_SECRET = L3OTWHLBYJADTD4V6DNZNTCHJNZVHH
KEYFILE         = ~/.xero/private.pem



[PUBLIC_APPLICATION]
# NAME            = 
# CONSUMER_KEY    = 
# CONSUMER_SECRET = 


[PARTNER_APPLICATION]
# NOT IMPLEMENTED YET
